Script started on Sun 25 Nov 2018 07:58:19 PM PST
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ make all
gcc -ansi -std=c99 -Wall -g -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -g -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -g -c  DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -g -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -g -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -g -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -lm PhotoLab.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -g -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -lm PhotoLab_DEBUG.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLabTest
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ ./
PhotoLab*     PhotoLabTest* 
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ ./PhotoLab
Invalid selection!

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
10: Resize the image
11: Saturate the image
12: Test all functions
13: Exit
Please make your choice: 12
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
90 degree right turn selected
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
Horizontal Flip Selected
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
You selected a percentage < 100
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
You selected a percentage > 100
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
10: Resize the image
11: Saturate the image
12: Test all functions
13: Exit
Please make your choice: 13
You exit the program.
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ ./PhotoLab[26Gmake all[K[26Gexit[Kcd hw4[26G~eecs22/bin/turnin.sh[26Gcd ..[K[26Gmv typescript PhotoLab.script[32Gr[55G[27Gake clean[K[26Gvalgrind --leak-check=full ./PhotoLabTest
==76448== Memcheck, a memory error detector
==76448== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==76448== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==76448== Command: ./PhotoLabTest
==76448== 
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
90 degree right turn selected
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
Horizontal Flip Selected
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
You selected a percentage < 100
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
You selected a percentage > 100
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.
==76448== 
==76448== HEAP SUMMARY:
==76448==     in use at exit: 0 bytes in 0 blocks
==76448==   total heap usage: 86 allocs, 86 frees, 12,433,008 bytes allocated
==76448== 
==76448== All heap blocks were freed -- no leaks are possible
==76448== 
==76448== For counts of detected and suppressed errors, rerun with: -v
==76448== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ make clean
rm -f *.o *.jpg rotate.ppm saturate.ppm hflip.ppm bigresize.ppm smallresize.ppm PhotoLab PhotoLabTest bw.ppm edge.ppm shuffle.ppm brightness.ppm hmirror.ppm hue.ppm \  libFilter.a
]0;dfchavar@laguna:~/hw4[dfchavar@laguna ~/hw4]$ exit
exit

Script done on Sun 25 Nov 2018 07:59:16 PM PST
